var blendModes = 'color,color-burn,color-dodge,darken,difference,exclusion,hard-light,hue,lighten,luminosity,multiply,normal,overlay,saturation,screen,soft-light'.split(',')
  , $banner
  , $ul
  , changeBlendModeIntervalRef;

function random (min, max) {
  return Math.floor(Math.random() * (max - min)) + min;
}

function setBannerBlendMode (idx) {
  $banner.style.backgroundBlendMode = blendModes[idx];

  // Set active box state
  for (let i = 0; i < blendModes.length; i++) {
    $ul.children[i].className = (i === idx) ? 'active' : '';
  }
}

function setup () {
  $banner = document.getElementById('banner');
  $ul = document.createElement('ul');

  // Remove original image (progressive enhancement)
  if ($banner.children.length) {
    $banner.children[0].remove();
  }

  // Make banner interactable
  // Add carousel-like selection boxes for active blend mode
  for (let li, i = 0; i < blendModes.length; i++) {
    li = document.createElement('li');
    li.title = blendModes[i];
    li.addEventListener('mousedown', function () {
      setBannerBlendMode(i);
      clearInterval(changeBlendModeIntervalRef);
    });
    $ul.appendChild(li);
  }
  $banner.appendChild($ul);
  $ul.children[blendModes.indexOf('normal')].dispatchEvent(new Event('mousedown'));

  // Add arrow key navigation (and vim support)
  document.addEventListener('keydown', function (event) {
    const keys = ["ArrowLeft", "j", "ArrowRight", "k"];
    const current = blendModes.indexOf($banner.style.backgroundBlendMode || 0);

    // Return early if key press isn't interesting
    if (keys.indexOf(event.key) < 0) {
      return;
    }

    // Don't auto-switch anymore
    clearInterval(changeBlendModeIntervalRef);

    let next;
    if (event.key === keys[0] || event.key === keys[1]) {
      next = current - 1;
    } else if (event.key === keys[2] || event.key === keys[3]) {
      next = current + 1;
    }

    // Wrap around when going out of bounds
    next = (next < 0) ? blendModes.length - 1: next % blendModes.length;
    setBannerBlendMode(next);
  });

  // Set random banner blend mode periodically
  changeBlendModeIntervalRef = setInterval(function () {
    setBannerBlendMode(random(0, blendModes.length));
  }, 20000);
}

document.addEventListener('DOMContentLoaded', setup, false);
console.log('This website was generated by my hands');
