apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: homepage
  name: homepage
  namespace: stigok
spec:
  replicas: 2
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: homepage
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: homepage
    spec:
      containers:
      - image: rg.fr-par.scw.cloud/fireto/stigok/stigok.com:latest
        imagePullPolicy: Always
        name: homepage
        resources:
          limits:
            cpu: 200m
            memory: 250Mi
          requests:
            cpu: 50m
            memory: 100Mi
      restartPolicy: Always
      terminationGracePeriodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  namespace: stigok
  name: homepage
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: homepage
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
  labels:
    app: homepage
  name: homepage
  namespace: stigok
spec:
  rules:
  - host: www.stigok.com
    http:
      paths:
      - backend:
          service:
            name: homepage
            port:
              number: 80
        path: /
        pathType: Prefix
  - host: stigok.com
    http:
      paths:
      - backend:
          service:
            name: homepage
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - stigok.com
    - www.stigok.com
    secretName: homepage-tls-cert
