name: Continous deployment

on:
  push:
    branches:
    - master
  pull_request: {}

jobs:
  build:
    runs-on: ubuntu-16.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # Create new image
    - name: Build and push Docker image
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        registry: ${{ secrets.DOCKER_REGISTRY }}
        repository: ${{ github.repository }}
        dockerfile: .deploy/Dockerfile
        path: .
        tags: latest
        tag_with_ref: true
        tag_with_sha: true

  deploy:
    needs: build
    runs-on: ubuntu-latest

    # Only deploy if pushed to master
    if: github.event_name == 'push' && github.ref == 'master'
    steps:
    - name: Update Kubernetes deployment container image
      uses: steebchen/kubectl@v1.0.0
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBECONFIG_DATA }}
      with:
        args: set image deploy/homepage nginx=${{ secrets.DOCKER_REGISTRY }}/${{ github.repository }}:${{ github.sha }}
