name: Continous deployment

on:
  push:
    branches:
    - master
  pull_request: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # Create new image
    - name: Build and push Docker image
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        registry: ${{ secrets.DOCKER_REGISTRY }}
        repository: ${{ github.repository }}
        dockerfile: .deploy/Dockerfile
        path: .
        tags: latest
        tag_with_ref: true
        tag_with_sha: true

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Update Kubernetes deployment container image
      uses: steebchen/kubectl@1.0.1
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBECONFIG_DATA }}
        KUBECTL_VERSION: "1.16"
      with:
        args: set image deploy/homepage nginx=${{ secrets.DOCKER_REGISTRY }}/${{ github.repository }}:${{ github.sha }}
