name: Continous deployment

on:
  push:
    branches:
    - master
  pull_request: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # Create new image
    - name: Build and push Docker image
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        registry: ${{ secrets.DOCKER_REGISTRY }}
        repository: ${{ github.repository }}
        dockerfile: .deploy/Dockerfile
        path: .
        tags: latest,${{ github.sha }}

  deploy:
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: azure/k8s-set-context@v1
        with:
          method: service-account
          k8s-url: ${{ secrets.K8S_API_URL }}
          k8s-secret: ${{ secrets.K8S_SECRET }}
      - name: Deploy
        uses: azure/k8s-deploy@v1
        with:
          namespace: stigok
          manifests: |
            .deploy/deployment.yaml
          images: |
            ${{ secrets.DOCKER_REGISTRY }}/${{ github.repository }}:${{ github.sha }}
